INSERT INTO themes (name, description) VALUES 
('Java', 'Programming language and related concepts'),
('Spring', 'Spring Framework and Spring Boot'),
('DevOps', 'Development operations and tools'),
('Database', 'Database concepts and technologies');

INSERT INTO words (word, theme_id) VALUES 
('class', 1),
('object', 1),
('method', 1),
('interface', 1),
('inheritance', 1),
('polymorphism', 1),
('encapsulation', 1),
('abstraction', 1),
('annotation', 1),
('lambda', 1),

('bean', 2),
('dependency', 2),
('injection', 2),
('autowired', 2),
('controller', 2),
('repository', 2),
('service', 2),
('configuration', 2),
('annotation', 2),
('boot', 2),

('docker', 3),
('kubernetes', 3),
('jenkins', 3),
('gitlab', 3),
('terraform', 3),
('ansible', 3),
('pipeline', 3),
('deployment', 3),
('container', 3),
('orchestration', 3),

('table', 4),
('query', 4),
('index', 4),
('transaction', 4),
('normalization', 4),
('relationship', 4),
('primarykey', 4),
('foreignkey', 4),
('constraint', 4),
('view', 4);